enum NameCase {
  uppercase
  lowercase
}

enum WeightType {
  lbs
  kgs
}

type Animal {
  id: ID!
  name(case: NameCase = lowercase): String!
  weight(weightType: WeightType = lbs): String!
  species: String!
  color: String!
  rescueDate: String
}

input AnimalQueryInput {
  case: NameCase = lowercase
  weightType: WeightType = lbs
}

input CreateAnimalInput {
  name: String!
  species: String!
  weight: Int
  color: String!
  rescueDate: String
}

input UpdateAnimalInput {
  name: String
  species: String
  weight: Int
  color: String
  rescueDate: String
}

type Query {
  animals: [Animal]!
  animal(id: ID!): Animal!
}

type Mutation {
  createAnimal(input: CreateAnimalInput): Animal!
  deleteAnimal(id: ID!): Animal!
  updateAnimal(id: ID!, input: UpdateAnimalInput!): Animal!
}
