enum Role {
  admin
  employee
}

type User {
  email: String!
  password: String!
  role: Role!
}

type Token {
  token: String!
}

input NewUserInput {
  email: String!
  password: String!
  role: Role!
}

input RegisterUserInput {
  email: String!
  password: String!
}

extend type Query {
  users: [User!]!
  user(id: ID!): User
}

extend type Mutation {
  createUser(input: NewUserInput!): User!
  registerUser(input: RegisterUserInput!): Token!
}
