enum Role {
  admin
  employee
  guest
}

type User {
  email: String!
  password: String!
  role: Role!
  createdAt: String
  updatedAt: String
  apiKey: String
}

input SignUpInput {
  email: String!
  password: String!
  role: Role!
}

input SignInInput {
  email: String!
  password: String!
}

extend type Query {
  users: [User!]!
  user(id: ID!): User

}
extend type Mutation {
  signUp(input: SignUpInput!): User!
  signIn(input: SignInInput!): User!
}
