type Animal {
  id: ID!
  name: String!
  species: String!
  weight: Int
  color: String!
  rescueDate: String
}

input AnimalInput {
  name: String!
  species: String!
  weight: Int
  color: String!
  rescueDate: String
}

input UpdateAnimalInput {
  name: String
  species: String
  weight: Int
  color: String
  rescueDate: String
}

type Query {
  animals: [Animal]!
  animal(id: ID!): Animal!
}

type Mutation {
  createAnimal(input: AnimalInput): Animal!
  deleteAnimal(id: ID!): Animal!
  updateAnimal(id: ID!, input: UpdateAnimalInput!): Animal!
}
